In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.datasets import load_digits

In [2]:
df = load_digits()
dir(df)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [10]:
x_train, x_test, y_train, y_test = train_test_split(df.data,df.target,test_size = 0.2)

In [11]:
len(x_test)

360

In [12]:
# For logistic
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [13]:
# For Support Vector Machine 

sv = SVC()
sv.fit(x_train,y_train)
sv.score(x_test,y_test)

0.9861111111111112

In [14]:
# For Random Forest
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9777777777777777

### Opr er gula efficient na krn train_test_split bar bar run
### korle test value gula change hobe jar krn e prediction 
### rate kom beshi hobe 

# try k fold cross

In [29]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [30]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [31]:
def get_score(model, x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [23]:
#get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)
# evabe check korte pari SVC() , LogicticRegression() esb boshiye

0.9694444444444444

In [32]:
from sklearn.model_selection import StratifiedKFold
hr = StratifiedKFold()
hr

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)

In [36]:
# eto boro esb lekhar drkr naai sudhu bujhar jonno je kivabe work kore 
score_logistic = []
score_svc = []
score_rf = []

for train_index, test_index in kf.split(df.data):
    x_train, x_test, y_train, y_test = df.data[train_index],df.data[test_index],df.target[train_index],df.target[test_index]
        
    score_logistic.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_svc.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_

In [37]:
score_logistic

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [38]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [39]:
score_rf

[0.9332220367278798, 0.9482470784641068, 0.9232053422370617]

In [40]:
# easy way 
from sklearn.model_selection import cross_val_score 

In [42]:
cross_val_score(LogisticRegression(),df.data,df.target)

G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [45]:
h1 = cross_val_score(SVC(),df.data,df.target)

In [44]:
cross_val_score(RandomForestClassifier(),df.data,df.target)

array([0.93055556, 0.91944444, 0.94986072, 0.96100279, 0.92479109])

In [49]:
a_h1 = np.mean(h1)

In [50]:
a_h1

0.9632838130609718

# Excercise with iris dataset

In [1]:
import numpy as np1
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris

In [3]:
f = load_iris()
dir(f)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [5]:
f.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
f.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
x_train, x_test, y_train, y_test = train_test_split(f.data,f.target,test_size = 0.2)

In [21]:
LR = LogisticRegression()
S_V = SVC()
RF = RandomForestClassifier()

In [22]:
LR.fit(x_train,y_train)
LR.score(x_test,y_test)

1.0

## same vabe baki gula  (ekhane bar bar score change hobe)

In [36]:
from sklearn.model_selection import KFold
KF = KFold()
KF

KFold(n_splits=5, random_state=None, shuffle=False)

In [26]:
#suppose
for train_index, test_index in KF.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
#as usual(not needed)
def get_Score (model1, x_train, x_test, y_train, y_test ):
    model1.fit(x_train, y_train)
    return model1.score(x_test,y_test)

In [30]:
get_Score(RandomForestClassifier(),x_train, x_test, y_train, y_test)

1.0

In [ ]:
# r ekta ase manually korar seta hoilo stratifiedkfold  (kfold er theke kisu better perform kore)

In [32]:
from sklearn.model_selection import StratifiedKFold
HR = StratifiedKFold()
HR

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)

In [50]:
score_L = []
score_SVC = []
score_RF = []

for train_index, test_index in KF.split(f.data):
    x_train, x_test, y_train, y_test = f.data[train_index],f.data[test_index],f.target[train_index],f.target[test_index]
    
    score_L.append(get_Score(RandomForestClassifier(),x_train, x_test, y_train, y_test))
    score_SVC.append(get_Score(LogisticRegression(),x_train, x_test, y_train, y_test))
    score_RF.append(get_Score(SVC(),x_train, x_test, y_train, y_test))

G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_

In [48]:
score_L

[1.0, 1.0, 0.8666666666666667, 0.9333333333333333, 0.7333333333333333]

## main way

In [51]:
from sklearn.model_selection import cross_val_score

In [54]:
new = cross_val_score(LogisticRegression(),f.data,f.target)
#cross_val_score(RandomForestClassifier(),f.data,f.target)
#cross_val_score(SVC(),f.data,f.target)

G:\Himel.conda\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [58]:
new1 = np1.average(new)
new1

0.9733333333333334

In [59]:
new2 = np1.mean(new)
new2

0.9733333333333334