In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('insurance_data.csv')
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [4]:
!pip install scikit-learn

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df[['age','affordibility']], df.bought_insurance, test_size = 0.2, random_state = 42)

In [8]:
x_train[:5]

age  affordibility
17   58              1
22   40              1
11   28              1
13   29              0
15   55              1

In [9]:
x_test

age  affordibility
9    61              1
25   54              1
8    62              1
21   26              0
0    22              1
12   27              0

In [10]:
x_train_scaled = x_train.copy()
x_test_scaled = x_test.copy()

x_train_scaled['age'] = x_train_scaled['age'] / 100
x_test_scaled['age'] = x_test_scaled['age'] / 100

In [11]:
x_test_scaled

age  affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

In [12]:
x_train_scaled[:5]

age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape = (2,), kernel_initializer='ones', activation='sigmoid')
])

model.compile(    
    optimizer = 'adam',
    loss = 'binary_crossentropy',
    metrics = ['accuracy'])

model.fit(x_train_scaled,y_train, epochs=5000)

Epoch 1/5000
1/1 [==============================] - 9s 9s/step - loss: 0.7428 - accuracy: 0.5000
Epoch 2/5000
1/1 [==============================] - 0s 47ms/step - loss: 0.7424 - accuracy: 0.5000
Epoch 3/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.7420 - accuracy: 0.5000
Epoch 4/5000
1/1 [==============================] - 0s 10ms/step - loss: 0.7416 - accuracy: 0.5000
Epoch 5/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.7411 - accuracy: 0.5000
Epoch 6/5000
1/1 [==============================] - 0s 16ms/step - loss: 0.7407 - accuracy: 0.5000
Epoch 7/5000
1/1 [==============================] - 0s 9ms/step - loss: 0.7403 - accuracy: 0.5000
Epoch 8/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.7399 - accuracy: 0.5000
Epoch 9/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.7395 - accuracy: 0.5000
Epoch 10/5000
1/1 [==============================] - 0s 16ms/step - loss: 0.7390 - accuracy: 0.5000
Epoch 11/500

In [17]:
model.evaluate(x_test_scaled, y_test)

1/1 [==============================] - 2s 2s/step - loss: 0.2647 - accuracy: 1.0000


[0.26470306515693665, 1.0]

In [18]:
model.predict(x_test_scaled)

1/1 [==============================] - 5s 5s/step


array([[0.81626713],
       [0.75767535],
       [0.82367426],
       [0.18819512],
       [0.38559142],
       [0.19598222]], dtype=float32)

In [19]:
y_test

9     1
25    1
8     1
21    0
0     0
12    0
Name: bought_insurance, dtype: int64

In [20]:
coef, intercept = model.get_weights()

In [21]:
coef

array([[5.018309 ],
       [1.1966311]], dtype=float32)

In [22]:
intercept

array([-2.766541], dtype=float32)

## How predicting works

In [23]:
import math
def sigmoid(z):
    return 1 / (1 + math.exp(-z))
    

In [24]:
#test
sigmoid(10)

0.9999546021312976

In [25]:
def predcition_fun(age, affordibility):
    y = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(y)

In [27]:
x_test_scaled[:2]

age  affordibility
9   0.61              1
25  0.54              1

In [28]:
y_test[:2]

9     1
25    1
Name: bought_insurance, dtype: int64

In [29]:
predcition_fun(0.61,1)

C:\Users\Himel\AppData\Local\Temp\ipykernel_10868\8305206.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-z))


0.816267109586199

In [30]:
predcition_fun(0.54,1)

C:\Users\Himel\AppData\Local\Temp\ipykernel_10868\8305206.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-z))


0.7576754121671682

# now  we build gredient descent and prove the coef and intercept

In [33]:
import numpy as np
def sigmoid_np(y):
    return 1 / (1 + np.exp(-y))

In [36]:
sigmoid_np(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

## Log Loss Function

In [39]:
np.log(0)

C:\Users\Himel\AppData\Local\Temp\ipykernel_10868\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [42]:
epsilon = 1e-15
def log_loss(y_true, y_predicted):
    y_pred_new = [max(i,epsilon)for i in y_predicted]
    y_pred_new1 = [min(i,1-epsilon)for i in y_pred_new]
    y_pred_new2 = np.array(y_pred_new1)


    return -np.mean((y_true*np.log(y_pred_new2)) + ((1-y_true) * np.log(1-y_pred_new2)))

In [49]:
# gradient descent

def gradient_descent(age, affordibility, y_true, epochs, loss_thresold):  # y_true is basically our truth value bought_insurance
    #w1,w2,bias
    w1 = w2 = 1
    bias = 0
    learning_rate = 0.5
    n = len(age)


    for i in range(epochs):
        y = w1*age + w2*affordibility + bias
        y_predicted = sigmoid_np(y)
        loss = log_loss(y_true, y_predicted)


        d_w1 = np.mean(age*(y_predicted - y_true)) # 1/n * (np.dot(np.transpose(age),(y_predicted - y_true)))

        d_w2 = np.mean(affordibility*(y_predicted - y_true)) # 1/n * (np.dot(np.transpose(affordibility),(y_predicted - y_true)))

        d_bias = np.mean((y_predicted - y_true))

        w1 = w1 - learning_rate*d_w1
        w2 = w2 - learning_rate*d_w2
        bias = bias - learning_rate*d_bias

        print(f'Epoch{i}-------w1: {w1},  w2: {w2}, bias: {bias}, loss: {loss}')

        if loss <= loss_thresold:
            break
    return w1,w2,bias

In [56]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train, 1000, 0.4921)

Epoch0-------w1: 0.9736899318847281,  w2: 0.931388810977659, bias: -0.11748951666770448, loss: 0.7428288579142563
Epoch1-------w1: 0.9536535852311093,  w2: 0.8740290167758512, bias: -0.21881533456146035, loss: 0.7072146449948487
Epoch2-------w1: 0.9393731039296968,  w2: 0.8271852202997496, bias: -0.3053620401943441, loss: 0.6814881914786812
Epoch3-------w1: 0.930193258899806,  w2: 0.7897792032048467, bias: -0.37884372361582785, loss: 0.6633428084673968
Epoch4-------w1: 0.9254091137248937,  w2: 0.7605726653866934, bias: -0.441082368200183, loss: 0.650742850709519
Epoch5-------w1: 0.9243325693598606,  w2: 0.738313053647322, bias: -0.4938425798625155, loss: 0.6420508089402462
Epoch6-------w1: 0.9263332963572349,  w2: 0.7218280753843739, bias: -0.5387319906498417, loss: 0.6360356979531206
Epoch7-------w1: 0.9308580975636879,  w2: 0.7100747303660235, bias: -0.5771558825717441, loss: 0.631816485354411
Epoch8-------w1: 0.9374354910317361,  w2: 0.7021560855322683, bias: -0.6103083840841516, lo

(5.0232237440063345, 1.2276138876500018, -2.8020335235526486)

In [57]:
coef

array([[5.018309 ],
       [1.1966311]], dtype=float32)

In [58]:
intercept

array([-2.766541], dtype=float32)