## Diabetes dataset from sklearn

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_diabetes
df = load_diabetes()

In [3]:
dir(df)

['DESCR',
 'data',
 'data_filename',
 'data_module',
 'feature_names',
 'frame',
 'target',
 'target_filename']

In [4]:
df.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [5]:
df.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [20]:
df.DESCR

'.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar

In [6]:
df.target_filename

'diabetes_target.csv.gz'

In [7]:
df1 = pd.DataFrame(df.data, columns = df.feature_names)
df1

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [8]:
df.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [9]:
df1['Target'] = df.target
df1

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  Target  
0   -0.002592  0.019907 -0.017646   151.0  
1   -0.039493 -0.068332 -0.092204    75.0  
2   -0.002592  0.002861 -0.025930   141.0  
3    0.034309  0.022688 -0.009362   206.0  
4   -0.002592 -0.031988 -0.046641   135.0  
..        ...       ...       ...     ...  
437 -0.002592  0.031193  0.007207   178.0  
438  0.034309 -0.018114  0.044485   104.0  
439 -0.011080 -0.046883  0.015491   132.0  
440  0.026560  0.044529 -0.025930   220.0  
441 -0.039493 -0.004222  0.003064    57.0  

[442 rows x 11 columns]

In [10]:
df1.sample(5)

age       sex       bmi        bp        s1        s2        s3  \
309 -0.009147  0.050680  0.001339 -0.002228  0.079612  0.070084  0.033914   
353 -0.052738 -0.044642 -0.055785 -0.036656  0.089244 -0.003193  0.008142   
264  0.034443  0.050680  0.028284 -0.033213 -0.045599 -0.009769 -0.050764   
54  -0.049105 -0.044642  0.025051  0.008101  0.020446  0.017788  0.052322   
90   0.012648 -0.044642 -0.025607 -0.040099 -0.030464 -0.045155  0.078093   

           s4        s5        s6  Target  
309 -0.002592  0.026717  0.081764   142.0  
353  0.034309  0.132376  0.003064   109.0  
264 -0.002592 -0.059471 -0.021788   145.0  
54  -0.039493 -0.041176  0.007207   182.0  
90  -0.076395 -0.072133  0.011349    98.0

In [11]:
df2 = df1.drop(['Target'], axis = 'columns')
df2.sample(5)

age       sex       bmi        bp        s1        s2        s3  \
330  0.009016  0.050680  0.030440  0.042529 -0.002945  0.036890 -0.065491   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
129  0.009016 -0.044642  0.016428  0.004658  0.009439  0.010586 -0.028674   
184  0.016281 -0.044642  0.023973 -0.022885 -0.024960 -0.026053 -0.032356   
434  0.016281 -0.044642  0.001339  0.008101  0.005311  0.010899  0.030232   

           s4        s5        s6  
330  0.071210 -0.023647  0.015491  
439 -0.011080 -0.046883  0.015491  
129  0.034309  0.038968  0.119043  
184 -0.002592  0.037236  0.032059  
434 -0.039493 -0.045424  0.032059

In [12]:
df3 = df1.Target
df3

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: Target, Length: 442, dtype: float64

In [21]:
from sklearn.model_selection import ShuffleSplit, cross_val_score, GridSearchCV
from sklearn.linear_model import LinearRegression, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

## Uisng Cross_val_Score

In [72]:
ss = ShuffleSplit(n_splits = 5, test_size = 0.1)
cross_val_score(RandomForestRegressor(random_state=1,n_estimators =  3000, max_depth=15), df2, df3, cv = ss)

array([0.54029678, 0.40322794, 0.45203913, 0.42278575, 0.28228721])

## Finding best model using GridSearchCV

In [73]:
def find_best_model(x,y):

    algo = {
        'LinearRegression': {
            'model' : LinearRegression(),
            'param' : {
                'n_jobs' : [1,2,3,4]
            }
        },

        'Lasso': {
            'model' : Lasso(),
            'param' : {
                'alpha': [1, 2, 3],
                'max_iter': [1000, 2000],
                'random_state': [10, 20, 42]
            }
        },

        'RandomForestRegressor': {
            'model' : RandomForestRegressor(),
            'param' : {
                'n_estimators': [100,200,3000],
                'max_depth': [10,15,20],
                'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
                'random_state': [1, 20, 42]
            }
        },

        'Support_Vec_R': {
            'model' : SVR(),
            'param' : {
                'kernel':['linear', 'poly', 'rbf', 'sigmoid'],
                'gamma':['scale', 'auto'],
                'C': [1,2,3],
                'max_iter': [10,20,100]
            }
        },

        'GradientBoostingRegressor' : {
            'model': GradientBoostingRegressor(),
            'param': {
                'loss': ['squared_error', 'absolute_error', 'huber', 'quantile'],
                'n_estimators': [100, 300, 1000],
                'criterion': ['friedman_mse', 'squared_error'],
                'max_depth': [10,15,20],
                'random_state': [1,20,42]
            }
        },
    }


    score = []

    ss = ShuffleSplit(n_splits=5, test_size=0.1)

    for model_name, config in algo.items():
        gs = GridSearchCV(config['model'], config['param'], cv = ss, return_train_score = False)
        gs.fit(x, y)
        score.append({
            'Model_Name': model_name,
            'Best_Score': gs.best_score_,
            'Best_EST': gs.best_estimator_
        })


    return pd.DataFrame(score, columns = ['Model_Name', 'Best_Score', 'Best_EST'])


result = find_best_model(df2,df3)
result

c:\Users\DCL\anaconda3\Lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\DCL\anaconda3\Lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\DCL\anaconda3\Lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\DCL\anaconda3\Lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn(
c:\Users\DCL\anaconda3\Lib\site-packages\sklearn\svm\_base.py:299: ConvergenceWarning: Solver terminated early (max_iter=10).  Consider pre-

KeyboardInterrupt: 

In [35]:
df2

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [36]:
df3

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: Target, Length: 442, dtype: float64

In [70]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df2, df3, test_size = 0.1, random_state=42)

In [71]:
model = GradientBoostingRegressor(random_state=1, n_estimators=1000, max_depth=10).fit(x_train, y_train)
print(model.score(x_test, y_test))

0.3712058088031269


In [66]:
model01 = RandomForestRegressor(random_state=1, n_estimators=3000, max_depth=15).fit(x_train, y_train)
print(model01.score(x_test, y_test))

0.5297982921007212
